// <auto-generated />
using System;
using MarketPrice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketPrice.Migrations
{
    [DbContext(typeof(MarketPriceDbContext))]
    [Migration("20251115164315_SeedingLookupDataType")]
    partial class SeedingLookupDataType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarketPrice.Models.Commodity", b =>
                {
                    b.Property<Guid>("CommodityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CommodityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CommodityTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short?>("LotSize")
                        .HasColumnType("smallint");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("ShelfLifeInDays")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("UnitOfMeasureId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CommodityId");

                    b.HasIndex("CommodityTypeId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("Commodities");
                });

            modelBuilder.Entity("MarketPrice.Models.CommodityType", b =>
                {
                    b.Property<Guid>("CommodityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CommodityGroupId")
                        .HasColumnType("int");

                    b.Property<Guid>("DefaultUnitOfMeasureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NameId")
                        .HasColumnType("int");

                    b.HasKey("CommodityTypeId");

                    b.HasIndex("CommodityGroupId");

                    b.HasIndex("DefaultUnitOfMeasureId");

                    b.HasIndex("NameId");

                    b.ToTable("CommodityTypes");
                });

            modelBuilder.Entity("MarketPrice.Models.DeliveryDetail", b =>
                {
                    b.Property<Guid>("DeliveryDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal?>("Fee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeliverable")
                        .HasColumnType("bit");

                    b.Property<string>("LeadTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MaxDistance")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DeliveryDetailId");

                    b.HasIndex("PositionId")
                        .IsUnique();

                    b.ToTable("DeliveryDetails");
                });

            modelBuilder.Entity("MarketPrice.Models.Location", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)");

                    b.Property<int>("LocationTypeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LocationId");

                    b.HasIndex("LocationTypeId");

                    b.HasIndex("RegionId");

                    b.HasIndex("UserId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("MarketPrice.Models.LookupData", b =>
                {
                    b.Property<int>("LookupDataId")
                        .HasColumnType("int");

                    b.Property<string>("LookupDataTextEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LookupDataTextFrench")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LookupDataTypeId")
                        .HasColumnType("int");

                    b.Property<string>("LookupDataValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LookupDataId");

                    b.HasIndex("LookupDataTypeId");

                    b.ToTable("LookupData");
                });

            modelBuilder.Entity("MarketPrice.Models.LookupDataType", b =>
                {
                    b.Property<int>("LookupDataTypeId")
                        .HasColumnType("int");

                    b.Property<string>("LookupDataTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LookupDataTypeId");

                    b.ToTable("LookupDataTypes");
                });

            modelBuilder.Entity("MarketPrice.Models.Position", b =>
                {
                    b.Property<Guid>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CommodityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PositionId");

                    b.HasIndex("CommodityId");

                    b.HasIndex("CurrentStatusId");

                    b.HasIndex("PositionTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("MarketPrice.Models.Rating", b =>
                {
                    b.Property<Guid>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RaterUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Score")
                        .HasColumnType("tinyint");

                    b.HasKey("RatingId");

                    b.HasIndex("RaterUserId");

                    b.HasIndex("RatedUserId", "RaterUserId")
                        .IsUnique();

                    b.ToTable("Ratings", t =>
                        {
                            t.HasCheckConstraint("CHK_Ratings_Score", "[Score] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("MarketPrice.Models.UnitOfMeasure", b =>
                {
                    b.Property<Guid>("UnitOfMeasureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("UnitOfMeasureCodeEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOfMeasureCodeFrench")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOfMeasureNameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOfMeasureNameFrench")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitOfMeasureId");

                    b.ToTable("UnitOfMeasures");
                });

            modelBuilder.Entity("MarketPrice.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("AccountTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsPremiumUser")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("IdCardNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MarketPrice.Models.Verification", b =>
                {
                    b.Property<Guid>("VerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("CurrentVerificationStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStarted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VerificationTypeId")
                        .HasColumnType("int");

                    b.HasKey("VerificationId");

                    b.HasIndex("CurrentVerificationStatusId");

                    b.HasIndex("UserId");

                    b.HasIndex("VerificationTypeId");

                    b.ToTable("Verifications");
                });

            modelBuilder.Entity("MarketPrice.Models.Commodity", b =>
                {
                    b.HasOne("MarketPrice.Models.CommodityType", null)
                        .WithMany()
                        .HasForeignKey("CommodityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketPrice.Models.UnitOfMeasure", null)
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketPrice.Models.CommodityType", b =>
                {
                    b.HasOne("MarketPrice.Models.LookupData", null)
                        .WithMany()
                        .HasForeignKey("CommodityGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MarketPrice.Models.UnitOfMeasure", null)
                        .WithMany()
                        .HasForeignKey("DefaultUnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketPrice.Models.LookupData", null)
                        .WithMany()
                        .HasForeignKey("NameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketPrice.Models.DeliveryDetail", b =>
                {
                    b.HasOne("MarketPrice.Models.Position", null)
                        .WithOne()
                        .HasForeignKey("MarketPrice.Models.DeliveryDetail", "PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketPrice.Models.Location", b =>
                {
                    b.HasOne("MarketPrice.Models.LookupData", null)
                        .WithMany()
                        .HasForeignKey("LocationTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MarketPrice.Models.LookupData", null)
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MarketPrice.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketPrice.Models.LookupData", b =>
                {
                    b.HasOne("MarketPrice.Models.LookupDataType", null)
                        .WithMany()
                        .HasForeignKey("LookupDataTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketPrice.Models.Position", b =>
                {
                    b.HasOne("MarketPrice.Models.Commodity", null)
                        .WithMany()
                        .HasForeignKey("CommodityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketPrice.Models.LookupData", null)
                        .WithMany()
                        .HasForeignKey("CurrentStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MarketPrice.Models.LookupData", null)
                        .WithMany()
                        .HasForeignKey("PositionTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MarketPrice.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketPrice.Models.Rating", b =>
                {
                    b.HasOne("MarketPrice.Models.User", null)
                        .WithMany()
                        .HasForeignKey("RatedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketPrice.Models.User", null)
                        .WithMany()
                        .HasForeignKey("RaterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketPrice.Models.User", b =>
                {
                    b.HasOne("MarketPrice.Models.LookupData", null)
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketPrice.Models.Verification", b =>
                {
                    b.HasOne("MarketPrice.Models.LookupData", null)
                        .WithMany()
                        .HasForeignKey("CurrentVerificationStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MarketPrice.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketPrice.Models.LookupData", null)
                        .WithMany()
                        .HasForeignKey("VerificationTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
